campusConnects/base/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import DetailView
from . import views

app_name = 'base'
urlpatterns = [

    path('registration/',views.registration,name="registration"),
    path('userRegistration/',views.UserRegistration,name="userRegistration"),
    path('login/',views.loginPage,name="login"),
    path('seemore/<int:pk>/',DetailView.as_view(), name='seemore'),
    # path('seemore/<int:pk>/increment_views/',views.incrementViews(),name='incrementViews'),
    path('profile/', views.profile, name='profile'),

]

# urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

campusConnects/campusConnects/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from base import views

urlpatterns = [
    path('',views.index,name="index"),
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('logout/',views.user_logout,name="logout"),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

campusConnects/base/models.py
from django.db import models
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.auth.models import User
# Create your models here.

class Event(models.Model):
    image = models.ImageField(null = True,blank = True, upload_to = 'media')
    title = models.CharField(max_length = 200)
    description = models.TextField()
    location = models.CharField(max_length = 200)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    register_link = models.URLField(null = True, blank = True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null = True)
    def __str__(self):
        return self.title

class EventAnalytics(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0)

campusConnects/base/forms.py
from django import forms
from .models import Event
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = ['title','image','description','location','start_date','end_date','register_link']
        # widgets = {
        #     'start_date': AdminDateWidget()),
        #     'end_date':  AdminDateWidget()),
        # }

class CreateUserform(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class PasswordResetForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            raise forms.ValidationError('No user with this email address.')
        return email

campusConnects/base/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.views import View
from .forms import EventForm,CreateUserform
from .models import Event
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

# Create your views here.
def index(request):
    event = Event.objects.all().values()
    temp = Event.objects.values_list('title')
    for i in temp[1]:
        print(i)
    context = {'event' : event}

    return render(request,'index.html',context)

def UserRegistration(request):
    form = CreateUserform()

    if request.method == 'POST':
        form = CreateUserform(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)

    context = {'form':form}
    return render(request,'userRegistration.html',context)

def loginPage(request):

    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request,username = username, password = password)

        if user is not None:
            login(request,user)

            return redirect('/profile')
        else:
            messages.success(request,("There was an error logging in.."))
            return redirect('/login')

    return render(request,'login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def registration(request):
    if request.method == "POST":
        form = EventForm(request.POST,request.FILES)
        if(form.is_valid()):
            event = form.save(commit = False)
            event.user = request.user
            form.save()
            return redirect('/profile')
    else:
        form = EventForm()
    context = {
        'form':form
    }

    return render(request,'registerForm.html',context)

@login_required
def profile(request):
    username = request.user.username
    user_objs = User.objects.get(username = username)
    print(user_objs)
    user = request.user.objects
    print(user)
    past_events = Event.objects.filter(user=user, end_date__lt=timezone.now())
    future_events = Event.objects.filter(user=user, start_date__gte=timezone.now())
    print(past_events)
    context = {'past_events': past_events,
                'user': user,
                'future_events': future_events}

    return render(request, 'profile.html', context)

def event_details(request):
    event = Event.objects.all()
    return render(request,'index.html',{'event' : event})

class DetailView(View):
    def get(self,request,pk,*args, **kwargs):
        detail = Event.objects.get(pk=pk)
        context = {'detail':detail}
        return render(request,'seemore.html',context)

# def incrementViews()

# def seemore(request,id):
#     event = get_object_or_404(Event,pk=id)
#     context = {'event':event}
#     return render(request,'seemore.html',context)

campusConnects/templates/base.html
{%load crispy_forms_tags %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>Home</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'base/css/homestyle.css'%}">
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap');
    </style>
  </head>
<body class="p-3 m-0 border-0 bd-example">
<div>
        <!-- <nav class="navbar bg-body-tertiary">
          <div class="container-fluid" style="height: 8vh;">
              <form class="d-flex" role="search">
              <div class="search">
                <input class="search" type="search" placeholder="Search" aria-label="Search"  >
                <button class="btn btn-outline-success" type="submit" fdprocessedid="ap3xpq" style="margin-left: 30px;">Search</button>
              </div>
              <div class="right-align">
                <div class="login">
                  <img src="{% static 'base/images/campus_logo.png'%}"  style="width: auto;height: 5vh;padding-left: 400px;">
                  <div style="padding-left: 590px;">
                    {% if user.is_authenticated %}
                    <button class="btn btn-outline-success" type="submit"><a href="{% url 'logout' %} ">Logout</a></button>
                    {% else %}
                    <button class="btn btn-outline-success" type="submit"><a href="{% url 'base:login' %} ">Login</a></button>
                    {% endif %}
                  </div>
                </div>
              </div>
              </form>
          </div>
        </nav> -->
        <div class="header">
          <input type="text" style="height: 5vh;width:220px;margin-left: 60px ;border-radius: 10px;border: none;" >
          <button class="x" type="submit" style="background-color: rgb(94, 94, 254); margin-left: 10px;height: 5vh;width: 110px ; border: none; border-radius: 10px;color: #F1F6F9;padding-top: 5px;"><h5>submit</h5></button>
          <img src="{% static 'base/images/campus_logo.png'%}" style="width: 170px;height:60px ;margin-left: 300px;padding-bottom: 5px;">


          <div class="topnav-right" style="float:right">
            {% if user.is_authenticated %}
            <button class="x"  style="background-color: rgb(94, 94, 254); margin-left:450px; height: 5vh;width: 110px;border: none; border-radius: 10px;color: #F1F6F9;padding-top: 5px;"><h5><a class = "logout-btn" href="{% url 'logout' %} ">Logout</a></h5></button>
            {% else %}
            <a class = "login-btn" href="{% url 'base:login' %} "><button class="x"  style="background-color: rgb(94, 94, 254); margin-left:450px; height: 5vh;width: 110px;border: none; border-radius: 10px;color: #F1F6F9;padding-top: 5px;"><h5>Login</h5></button></a>
            {% endif %}

          </div>

        </div>
        <!-- <div class="topnav">
          <img src="{% static 'base/images/campus_logo.png'%}" style="width: 170px;height:60px ;margin-left: 10px;padding-bottom: 5px;">
          <a href="#">Ongoing Events</a>
          <a href="#">Upcoming Events</a>
          <a href="#">Contact Us</a>
          <div class="topnav-right">
            <a href="#">Login</a>

          </div>
        </div> -->

    {% if user.is_authenticated %}
    <div class="jumbotron">
      <h3>Register for your event here..</h3>
      <button class="btn btn-outline-success" type="submit"><a class = "register" href="{% url 'base:registration' %} ">Register</a></button>
    </div>
    <br><br>
    {% endif %}
    {% block content %}

    {% endblock content%}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

campusConnects/templates/index.html
{%extends 'base.html'%}

{%block content%}
<br><br>
<pre class="h">    ONGOING EVENTS<br></pre>




<div class="ongoing" style="display: flex;">
  {% include 'ongoing.html' %}

</div>
<br>
<hr><hr>
<br>
<pre class="h">UPCOMING EVENTS<br></pre>
<br>
<div class="upcomming" style="display: flex;">

  {% include "upcoming.html" %}


  </div>
</div>
</div>
<br><br>
<div class="footer" style="background-color: #0B2447;color: #F1F6F9; width: 100% ;text-align: center;"><br>
  <p>2020 arfa, Inc. All rights reserved.</p>
  <p>for any queries and admin access</p>
  <p style="font-weight: bold;font-size: medium;"> Contact us</p>
      <button class="x"  style="background-color: rgb(94, 94, 254);margin-right: 10px;height: 5vh;width: 110px;border: none; border-radius: 10px;color: #F1F6F9;padding-top: 5px;"><h6>Whatsapp</h6></button>
      <button class="x"  style="background-color: rgb(94, 94, 254);height: 5vh;width: 110px;border: none; border-radius: 10px;color: #F1F6F9;padding-top: 5px;"><h6>Gmail</h6></button>

  <br><br>
</div>
{% endblock %}

campusConnects/templates/login.html
{%extends 'base.html'%}

{%block content%}
<style media="screen">
  body{
      /* background-image:  url('a.jpg'); */
      background-repeat: no-repeat;
      background-size: cover;
      background-attachment: fixed;
      /* backdrop-filter: blur(5px); */
      background: rgb(103,105,106);
background: linear-gradient(90deg, rgba(103,105,106,1) 0%, rgba(75,151,240,1) 100%);
      width: 100%;
      height: 100%;
  }
</style>
<form method="post" action="">
  {% csrf_token %}
    <div class="content">
        <h1 class="a">Login</h1><br>
        <label>Username : </label> <br>
        <input type="text" placeholder="Enter Username" name="username" required class="b"><br><br>
        <label>Password : </label> <br>
        <input type="password" placeholder="Enter Password" name="password" required class="b"><br><br>
        {% if messages %}
          {% for message in messages %}
            {{message}}
          {% endfor %}
        {% endif %}
        <br><br>
        <button type="submit">Login</button> <br><br>
        <input type="checkbox" checked="checked"> Remember me
        <a href="#">  Forgot password? </a>
    </div>
</form>

{% endblock %}

campusConnects/templates/ongoing.html
{% load static %}

{% for i in event %}
<div>
  <div class="card" style="width: 18rem;">
    <img src="/media/{{i.image}}" class="card-img-top" >
    <div class="card-body">
      <h5 class="card-title">{{i.title}}</h5>

      <p class="card-text">{{i.description}} >> {{i.image}}</p>
      <!-- <p>{{seemore.get_absolute_url}}</p> -->
      <a href="#" class="btn btn-primary">Register Now</a>
      <a href="{% url 'base:seemore' i.id %}" class="btn btn-primary"  style="width: 45%;background-color: green;color: #F1F6F9">See more</a>
    </div>
  </div>
</div>
<!-- <div>
  <div class="card" style="width: 18rem;#0B2447">
    <img src="c.jpg" class="card-img-top" >
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn btn-primary " >Register Now</a>
      <a href="#" class="btn btn-primary"  style="width: 45%;background-color: #0B2447;color: #F1F6F9">See more</a>
    </div>
  </div>
</div> -->

{% endfor %}

campusConnects/templates/profile.html
{%extends 'base.html'%}

{%block content%}
<h1>Hello! {{user.username}}</h1>
<h2>Profile</h2>
<h3>Past Events:</h3>
<ul>
  {% for i in past_events %}
  <div class="past-events">
    <div class="card" style="width: 18rem;">
      <img src="/media/{{i.image}}" class="card-img-top" >
      <div class="card-body">
        <h5 class="card-title">{{i.title}}</h5>

        <p class="card-text">{{i.description}} >> {{i.image}}</p>
        <!-- <p>{{seemore.get_absolute_url}}</p> -->
        <a href="#" class="btn btn-primary">Register Now</a>
        <a href="{% url 'base:seemore' i.id %}" class="btn btn-primary"  style="width: 45%;background-color: green;color: #F1F6F9">See more</a>
      </div>
    </div>
  </div>
  {% empty %}
    <li>No past events.</li>
  {% endfor %}
</ul>

<h3>Future Events:</h3>
<ul>
  {% for event in future_events %}
    <li>{{ event.name }}</li>
  {% empty %}
    <li>No future events.</li>
  {% endfor %}
</ul>
{% endblock %}

campusConnects/templates/registerForm.html
{% extends 'base.html' %}
{%load crispy_forms_tags %}
{%block content%}
<form class="" action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" name="button">Submit</button>

</form>
{% endblock %}

campusConnects/templates/seemore.html
{% extends 'base.html' %}

{%block content%}
<style media="screen">
  .a{

      background-image: linear-gradient(to right,#0b2447, #DFF6FF,#0b2447);
      height: 100vh;
      width: 100%;
      position: fixed;

  }
  .scroller-card {
      height: 600px;
      width: 60%;
      overflow-y: scroll;
      background-color: #DFF6FF;
      margin-left: auto;
      margin-right: auto;
      border-radius: 30px;
      margin-top: 70px;
      box-shadow: inset 0px 5px 10px 0px rgba(76, 113, 148, 0.7);
    }

  .scroller {
      display: flex;
      flex-direction: column;
      align-items: center;
    }

   .x{
      background-color: #0b2447;
      color:#DFF6FF;
      width: 100%;
      height: 10vh;
      font-size: 50px;
      font-weight:bolder;
      font-family: cursive;
      text-align: center;
   }
   .z{
      font-size: 40px;
      width: 100%;
      text-align: center;
      font-weight:bold;
      font-family: cursive;
      color:#DFF6FF;
      background-color: #5b859d;

   }

   .y{
      width: 80%;
      align-items: center;
      text-align: center;
   }


   @media (max-width: 767px) {
      .scroller-card {
          padding: 10px;
      }
      .y {
          padding: 0;
      }
      .y img {
          width: 100%;
          height: auto;
          border-radius: 0;
      }
      .x {
          font-size: 18px;
          height: auto;
          width: 100%;
      }
  }




</style>
<div class="a">
<div class="scroller-card">
    <div class="scroller">
            <p class="card-text">
                <p class="x">Google Developer Student Clubs</p>
                <p class="z">{{detail.title}}</p>
                <hr>
                <div class="y">
                    <div><img src="/media/{{detail.image}}" style="width: 350px;height: 450px;border-radius: 20px;"> </div><br><br>
                    <div style="background-color: #0B2447;color: #DFF6FF;border-radius: 20px;"><p><br>
                        long description



                    <br>
                    <br>
                    </p></div>
                </div><br>
                <!-- <div> <img src="qr_code_barcode.jpg" style="width: 150px;height: 150px;"> </div><br> -->
                <button class="x"  style="background-color: rgb(94, 94, 254);height: 8vh;width: 210px;border: none; border-radius: 10px;color: #F1F6F9;"><h5>Register Now</h5></button><br>
            </p>
    </div>
</div>
</div>





{% endblock %}

campusConnects/templates/upcoming.html
{% load static %}
{% for i in event %}
<div>
  <div class="card" style="width: 18rem;">
    <img src="/media/{{i.image}}" class="card-img-top" >
    <div class="card-body">

      <h5 class="card-title">{{i.title}}</h5>
      <p class="card-text">{{i.description}}</p>

      <a href="#" class="btn btn-primary">Register Now</a>
      <a href="{% url 'base:seemore' i.id %}" class="btn btn-primary" style="width: 45%;background-color: #0B2447;color: #F1F6F9">See more</a>
    </div>
  </div>
</div>
{% endfor %}

campusConnects/templates/userRegistration.html
{%extends 'base.html'%}

{%block content%}
<style media="screen">
  body{
      /* background-image:  url('a.jpg'); */
      background-repeat: no-repeat;
      background-size: cover;
      background-attachment: fixed;
      /* backdrop-filter: blur(5px); */
      background: rgb(2,0,36);
      background: linear-gradient(240deg, rgba(2,0,36,1) 0%, rgba(1,37,51,0.8303960006429542) 46%, rgba(5,210,249,1) 100%);
      width: 100%;
      height: 100%;
  }
</style>
<form class="" action="" method="post">
  {% csrf_token %}
    <div class="content">
        <h1 class="a">Register</h1><br>
        <label>Username : </label> <br>
        {{form.username}}<br><br>
        <label>Email : </label> <br>
        {{form.email}}<br><br>
        <label>Password : </label> <br>
        {{form.password1}}<br><br>
        <label>Confirm Password : </label> <br>
        {{form.password2}}<br><br>
        {{form.errors}}
        {% for message in messages %}
          <p>{{message}}</p>
        {% endfor %}
        <button class="login-btn" type="submit">Register</button> <br><br>
        <input type="checkbox" checked="checked"> Remember me
        <a href="#">  Forgot password? </a>
    </div>
</form>
<!-- <form class="" action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" name="" value="">
</form> -->


{% endblock %}